### ISSUE TITLE
new Issue still cannot install GTK::Simple error during tests 

### ISSUE THREAD

**Issue by grizzlysmit** [finanalyst/GTK-Simple#20] opened 2015-12-25 21:58 UTC
panda install GTK::Simple
==> Fetching GTK::Simple
==> Building GTK::Simple
Found system gtk library.
==> Testing GTK::Simple
# Failed test at t/01_sanity.t line 6
# Cannot locate native library 'libgtk-3': libgtk-3: cannot open shared object file: No such file or directory
# Failed test at t/01_sanity.t line 7
# Cannot locate native library 'libglib-2.0': libglib-2.0: cannot open shared object file: No such file or directory
# Failed test at t/01_sanity.t line 8
# Method 'run' not found for invocant of class 'Any'
# Looks like you failed 3 tests of 3

t/01_sanity.t .. 
Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/3 subtests 
## Test Summary Report

t/01_sanity.t (Wstat: 768 Tests: 3 Failed: 3)
  Failed tests:  1-3
  Non-zero exit status: 3
Files=1, Tests=3, 152 wallclock secs ( 0.04 usr  0.00 sys + 43.26 cusr  1.23 csys = 44.53 CPU)
Result: FAIL
The spawned process exited unsuccessfully (exit code: 1)
  in sub run-and-gather-output at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/BC95C1F03FD26FCC92CB72CD826C4739353C6CA6:85
  in block  at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/FC684EC9B9C25726CC880847EFF9969D1A73521D:22
  in sub indir at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/BC95C1F03FD26FCC92CB72CD826C4739353C6CA6:20
  in method test at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/FC684EC9B9C25726CC880847EFF9969D1A73521D:5
  in method install at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/BA0F30DD085F36D1DDB7AB73A230AF22CC30C87B:141
  in method resolve at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/BA0F30DD085F36D1DDB7AB73A230AF22CC30C87B:219
  in sub MAIN at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/resources/41715A941E28E09D8BF7F4B447720F8C0E01F976:18
  in block <unit> at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/resources/41715A941E28E09D8BF7F4B447720F8C0E01F976:150

// so I try to locate the missing library:
locate libgtk-3.so
/usr/lib/i386-linux-gnu/libgtk-3.so
/usr/lib/i386-linux-gnu/libgtk-3.so.0
/usr/lib/i386-linux-gnu/libgtk-3.so.0.1600.7

it's there why doesn't GTK::Simple find it should I symlink it some where??

**Comment by Skarsnik** [comment] 2015-12-26 00:42
The issue is with some recent change in the way NativeCall find the library. 
You could pass a path/lib name or even a routine and NC will try to build the file path according to some information (plateform, the way the argument look like...). Now if you just pass a routine it let you at your own device. (like not adding .so on Linux, as the error show)

The proper change in the gtk::simple would probably be to not pass a routine to the native trait but a build a variable to pass around with these routine

**Comment by stmuk** [comment] 2015-12-26 00:48
NativeCall no longer needs the leading "lib" part of a library.  I quickly
tried changing those refs but it still didn't work so I think other changes
are necessarily.

On 26 December 2015 at 00:42, Skarsnik notifications@github.com wrote:

> The issue is with some recent change in the way NativeCall find the
> library.
> You could pass a path/lib name or even a routine and NC will try to build
> the file path according to some information (plateform, the way the
> argument look like...). Now if you just pass a routine it let you at your
> own device. (like not adding .so on Linux, as the error show)
> 
> The proper change in the gtk::simple would probably be to not pass a
> routine to the native trait but a build a variable to pass around with
> these routine
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/perl6/gtk-simple/issues/20#issuecomment-167268662.

## 

4096R/EA75174B Steve Mynott steve.mynott@gmail.com

**Comment by grizzlysmit** [comment] 2015-12-26 01:16
I tried setting LD_LIBRARY_PATH but no good

**Comment by Skarsnik** [comment] 2015-12-26 01:53
Changing what the routine returns to something NC understand in a normal use of the is native trait will not work.
The routine in charge of guessing a libname/path work like that:
If the argument is a Str: do some magic
If the argument is a List  (name, version) : do some magic
If the argument is a Callable :  call the function and get the value returned and do nothing to it

What happen here :  NC call one of this function that return "libgtk3" keep this value and dlopen will use that, and fail because it can't find this filename in the LD paths.

You etheir need to replace the is native(&libgtk) with a is native('gtk3', v0) or tweak the libgtk to return a valid path name. Another solution is to have a my $libgtk3 = libgtk() and do is native($libgtk3)

**Comment by niner** [comment] 2015-12-26 09:20
commit 2188c5ffbed4508a429b1cb10c8242f1c0937a50 fixes this issue on non-Windows. For Windows the find-bundled code should be replaced by accessing %*RESOURCES. That probably needs some changes to the packaging, too.

**Comment by grizzlysmit** [comment] 2015-12-26 17:33
it works now on Linux (Ubuntu 15.10) but I have found a new issue: when I run the following code 

<pre>
#!/usr/bin/env perl6
use v6;
use GTK::Simple;
my GTK::Simple::App $app .= new(title => "Bad!");
$app.set_content(
        my $btn = GTK::Simple::Button.new(label => "button")
    );
$app.border_width = 20;
$btn.clicked.tap(-> $me { "button clicked {$me.perl}".say; });
$app.run;
</pre>

When I run this code I get the following:

<pre>
./bad2.p6 
Cannot directly create a Supply. You might want:
 - To use a Supplier in order to get a live supply
 - To use Supply.on-demand to create an on-demand supply
 - To create a Supply using a supply block
  in method clicked at /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/545DAA3C25435C0D4CBDE98E2DDD66E514443B13 line 600
  in block <unit> at ./bad2.p6 line 14
</pre>

I looked in /home/grizzlysmit/.rakudobrew/moar-nom/install/share/perl6/site/sources/545DAA3C25435C0D4CBDE98E2DDD66E514443B13
and found lines like my $s = Supply.new;
but http://doc.perl6.org/type/Supply contains this on the subject of Supply:
"A live Supply is obtained from the Supplier factory method Supply. New values are emitted by calling emit on the Supplier object."

<pre>
my $supplier = Supplier.new;
my $supply = $supplier.Supply;
$supply.tap(-> $v { say "$v" });
$supplier.emit(42); # Will cause the tap to output "42"
</pre>

so I changed the file so that every instance of my $s = Supply.new;
became 
my $supplier = Supplier.new;
my $s = $supplier.Supply;
and the corresponding $s.emit(self) became: $supplier.emit(self) or in one or two cases the args were different (i.e. not self) but I just made them $supplier.emit(args), and voila the my bad.p6 and bad2.p6 worked as did my larger example

**Comment by jonathanstowe** [comment] 2015-12-26 18:58
Thanks.

**Comment by jonathanstowe** [comment] 2015-12-26 19:22
That last should be fixed in https://github.com/perl6/gtk-simple/commit/69b1ee44a1864c606181b281abc8e937c9e5f32a if you want to reinstall with panda you will need to do "panda --force install GTK::Simple".

**Comment by grizzlysmit** [comment] 2015-12-27 11:37
Thanks that did the trick

**Closed as completed** 2015-12-27 11:38 UTC
